// Filtered from https://en.ilmatieteenlaitos.fi/observation-stations
const stations = [
  'Ähtäri',
  'Alajärvi',
  'Asikkala',
  'Enontekiö',
  'Espoo',
  'Hailuoto',
  'Hämeenlinna',
  'Hammarland',
  'Hanko',
  'Hattula',
  'Heinola',
  'Helsinki',
  'Hyvinkää',
  'Ilmajoki',
  'Ilomantsi',
  'Inari',
  'Inkoo',
  'Jämsä',
  'Järvenpää',
  'Joensuu',
  'Jomala',
  'Joutsa',
  'Juuka',
  'Juva',
  'Jyväskylä',
  'Kaarina',
  'Kajaani',
  'Kalajoki',
  'Kankaanpää',
  'Karvia',
  'Kaskinen',
  'Kauhajoki',
  'Kauhava',
  'Kemi',
  'Kemijärvi',
  'Kemiönsaari',
  'Kirkkonummi',
  'Kittilä',
  'Kökar',
  'Kokemäki',
  'Kokkola',
  'Korsnäs',
  'Kotka',
  'Kouvola',
  'Kristiinankaupunki',
  'Kruunupyy',
  'Kuhmo',
  'Kumlinge',
  'Kuopio',
  'Kustavi',
  'Kuusamo',
  'Lahti',
  'Lappeenranta',
  'Lemland',
  'Lieksa',
  'Liperi',
  'Lohja',
  'Loviisa',
  'Luhanka',
  'Lumparland',
  'Maalahti',
  'Maarianhamina',
  'Mäntsälä',
  'Mariehamn',
  'Mikkeli',
  'Multia',
  'Muonio',
  'Mustasaari',
  'Nurmes',
  'Nurmijärvi',
  'Oulu',
  'Parainen',
  'Parikkala',
  'Pelkosenniemi',
  'Pello',
  'Pietarsaari',
  'Pirkkala',
  'Pori',
  'Porvoo',
  'Pudasjärvi',
  'Puolanka',
  'Puumala',
  'Pyhäjärvi',
  'Pyhtää',
  'Raahe',
  'Raasepori',
  'Rantasalmi',
  'Ranua',
  'Rauma',
  'Rovaniemi',
  'Salla',
  'Salo',
  'Savonlinna',
  'Savukoski',
  'Seinäjoki',
  'Siikajoki',
  'Siilinjärvi',
  'Sipoo',
  'Sodankylä',
  'Somero',
  'Sotkamo',
  'Suomussalmi',
  'Taivalkoski',
  'Tampere',
  'Tervola',
  'Tohmajärvi',
  'Toholampi',
  'Tornio',
  'Turku',
  'Utsjoki',
  'Vaala',
  'Vaasa',
  'Vantaa',
  'Varkaus',
  'Vesanto',
  'Vieremä',
  'Vihti',
  'Viitasaari',
  'Virolahti',
  'Virrat',
  'Ylitornio',
  'Ylivieska',

  'Haapavesi',
  'Halsua',
  'Rautavaara',
  'Juupajoki',
  'Jokioinen',

  'Enontekiö airport',
  'Halli airport',
  'Ivalo airport',
  'Joensuu airport',
  'Jyväskylä airport',
  'Kajaani airport',
  'Kemi-Tornio airport',
  'Kittilä airport',
  'Kuusamo airport',
  'Lappeenranta airport',
  'Oulu airport',
  'Pori airport',
  'Savonlinna airport',
  'Seinäjoki airport',
  'Tampere-Pirkkala airport',
  'Utti airport',
];

export function getCloudnessStations(): string[] {
  return stations;
}
